[package]
name = "debug_joe"
version = "0.1.0"
authors = ["Joe Gdaniec <jgdaniec@gmail.com>"]

[dependencies]
serde_json = "0.8"
serde_codegen = "0.8.16"
rnet = {git = "https://github.com/jjgz/rnet"}
